apiVersion: v1
kind: ConfigMap
metadata:
  namespace: production
  name: init-sql-config 
data:
  init.sql: |
    CREATE DATABASE test1;

    USE test1;

    CREATE TABLE users (
      id INT PRIMARY KEY AUTO_INCREMENT,
      name VARCHAR(250) NOT NULL,
      email VARCHAR(250) UNIQUE,
      phone VARCHAR(100),
      bgroup VARCHAR(100)
    );
