kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /path/on/your/host
        containerPath: /mnt/disks
  - role: worker
    extraMounts:
      - hostPath: /path/on/your/host
        containerPath: /mnt/disks
  - role: worker
    extraMounts:
      - hostPath: /path/on/your/host
        containerPath: /mnt/disks
