version: '3.8'

services:
  jenkins:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "80:8080"    #Map to local port 80
      - "50000:50000"
    volumes:
      - /home/kuba/plugins_required/my_tutorials/gitlab+jenkins/jenkins/jenkins_home:/var/jenkins_home
      - ./jenkins-casc.yaml:/var/jenkins_conf.yaml
      - ./ssh_config/config:/var/jenkins_home/.ssh/config
      - ./ssh_config/gitlab-key:/var/jenkins_home/.ssh/gitlab-key
    restart: unless-stopped
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf.yaml
