jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "kuba"
          password: "kuba"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "TERRAFORM_CLOUD_TOKEN"
          id: "TERRAFORM_CLOUD_TOKEN"
          scope: GLOBAL
          secret: "{AQAAABAAAAAQ2wgdZxOyWxSIsEGgdxW+uVje3oed/A//QTYijQinDnI=}"
