version: '3'

services:
  my_ubuntu:
    image: ubuntu:latest
    command: tail -f /dev/null # Trzyma kontener w stanie uruchomionym

  my_rb:
    image: rabbitmq:3-management
    hostname: rb
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672" # Port interfejsu zarządzania RabbitMQ
      - "5672:5672"   # Port serwera AMQP RabbitMQ

