version: '3'
services:
  apache:
    image: httpd:2.4
    container_name: 'apache'
    restart: always
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - '80:80'

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    restart: always
    hostname: 'gitlab.domain.com'
    depends_on:
      - apache
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.domain.com/gitlab'
    ports:
      - '8081:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'

