version: '3.8'

services:
  jenkins:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "80:8080"    #Map to local port 80
      - "50000:50000"  #Port dla agentów
    volumes:
      - jenkins_data:/var/jenkins_home  
      - ./jenkins-casc.yaml:/var/jenkins_conf.yaml
      - ./ssh_config/config:/var/jenkins_home/.ssh/config
      - ./ssh_config/gitlab-key:/var/jenkins_home/.ssh/gitlab-key
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf.yaml

volumes:
  jenkins_data:
    driver: local 
